"""Tier-1 medication catalog: ~75 commonly-used-in-Armenia medications,
each with canonical name, OpenFDA search term, category, and a list of
variants spanning typos, Cyrillic, Armenian, and Russian/local brand names.

Format:
{
  "canonical": "Paracetamol",
  "openfda_term": "Acetaminophen",
  "category": "Pain/Fever",
  "variants": [list of typos / translations / brand names]
}

The Matcher normalizes (script-transliterated, lowercased, punctuation
stripped) every variant + canonical name and indexes them for both
exact and fuzzy lookup.
"""
from typing import List, Dict


MEDICATION_CATALOG: List[Dict] = [
    # ─── ANTIBIOTICS ────────────────────────────────────────────
    {"canonical": "Amoxicillin", "openfda_term": "Amoxicillin",
     "category": "Antibiotic",
     "variants": ["amoxicillin", "amoxicilin", "amoksisilin", "amoksicillin",
                  "амоксициллин", "амоксицилин", "ամոքսիցիլին",
                  "Amoxil", "amoxil", "Амоксил", "Augmentin", "augmentin"]},
    {"canonical": "Azithromycin", "openfda_term": "Azithromycin",
     "category": "Antibiotic",
     "variants": ["azithromycin", "azitromicin", "azitromycin",
                  "азитромицин", "ազիթրոմիցին",
                  "Sumamed", "sumamed", "Сумамед", "Zithromax", "zithromax",
                  "Hemomycin", "hemomycin"]},
    {"canonical": "Ciprofloxacin", "openfda_term": "Ciprofloxacin",
     "category": "Antibiotic",
     "variants": ["ciprofloxacin", "ciprofloksacin", "ципрофлоксацин",
                  "ցիպրոֆլոքսացին", "cipro", "Ципролет", "Ciprolet",
                  "ciprolet", "Cipronol", "cipronol"]},
    {"canonical": "Doxycycline", "openfda_term": "Doxycycline",
     "category": "Antibiotic",
     "variants": ["doxycycline", "doksiciklin", "доксициклин",
                  "դոքսիցիկլին", "Vibramycin", "vibramycin",
                  "Юнидокс", "Unidox"]},
    {"canonical": "Metronidazole", "openfda_term": "Metronidazole",
     "category": "Antibiotic",
     "variants": ["metronidazole", "metronidazol", "метронидазол",
                  "մետրոնիդազոլ", "Flagyl", "flagyl", "Флагил",
                  "Трихопол", "trichopol", "trihopol"]},
    {"canonical": "Clarithromycin", "openfda_term": "Clarithromycin",
     "category": "Antibiotic",
     "variants": ["clarithromycin", "klaritromicin", "кларитромицин",
                  "Klacid", "klacid", "Клацид", "Fromilid", "fromilid"]},
    {"canonical": "Ceftriaxone", "openfda_term": "Ceftriaxone",
     "category": "Antibiotic",
     "variants": ["ceftriaxone", "ceftriakson", "цефтриаксон",
                  "ցեֆտրիաքսոն", "Rocephin", "rocephin"]},
    {"canonical": "Levofloxacin", "openfda_term": "Levofloxacin",
     "category": "Antibiotic",
     "variants": ["levofloxacin", "levofloksacin", "левофлоксацин",
                  "Tavanik", "tavanik", "Таваник", "Levaquin", "levaquin"]},
    {"canonical": "Ampicillin", "openfda_term": "Ampicillin",
     "category": "Antibiotic",
     "variants": ["ampicillin", "ampicilin", "ампициллин", "ամպիցիլին"]},
    {"canonical": "Tetracycline", "openfda_term": "Tetracycline",
     "category": "Antibiotic",
     "variants": ["tetracycline", "tetraciklin", "тетрациклин",
                  "տետրացիկլին"]},

    # ─── PAIN / FEVER ───────────────────────────────────────────
    {"canonical": "Paracetamol", "openfda_term": "Acetaminophen",
     "category": "Pain/Fever",
     "variants": ["paracetamol", "parcetamol", "paratsetamol",
                  "парацетамол", "պարացետամոլ",
                  "Panadol", "panadol", "Панадол", "Тайленол", "Tylenol",
                  "tylenol", "acetaminophen", "Эффералган", "Efferalgan"]},
    {"canonical": "Ibuprofen", "openfda_term": "Ibuprofen",
     "category": "Pain/Fever",
     "variants": ["ibuprofen", "ibuprofin", "ибупрофен",
                  "իբուպրոֆեն",
                  "Nurofen", "nurofen", "Нурофен", "Advil", "advil", "Адвил",
                  "Brufen", "brufen", "Mig", "Долгит"]},
    {"canonical": "Aspirin", "openfda_term": "Aspirin",
     "category": "Pain/Fever",
     "variants": ["aspirin", "asprin", "aspiren", "аспирин", "Аспирин",
                  "ասպիրին", "Acetylsalicylic acid",
                  "Ascard", "Cardiomagnyl"]},
    {"canonical": "Diclofenac", "openfda_term": "Diclofenac",
     "category": "Pain/Fever",
     "variants": ["diclofenac", "diklofenak", "диклофенак",
                  "դիկլոֆենակ", "Voltaren", "voltaren", "Вольтарен",
                  "Olfen", "Diclac"]},
    {"canonical": "Ketorolac", "openfda_term": "Ketorolac",
     "category": "Pain/Fever",
     "variants": ["ketorolac", "ketorolak", "кеторолак", "Ketorol", "ketorol",
                  "Кеторол", "Toradol"]},
    {"canonical": "Naproxen", "openfda_term": "Naproxen",
     "category": "Pain/Fever",
     "variants": ["naproxen", "naproksen", "напроксен",
                  "Nalgesin", "nalgesin", "Налгезин", "Aleve"]},
    {"canonical": "Meloxicam", "openfda_term": "Meloxicam",
     "category": "Pain/Fever",
     "variants": ["meloxicam", "meloksikam", "мелоксикам",
                  "Movalis", "movalis", "Мовалис", "Mobic"]},
    {"canonical": "Nimesulide", "openfda_term": "Nimesulide",
     "category": "Pain/Fever",
     "variants": ["nimesulide", "nimesulid", "нимесулид",
                  "Naiz", "naiz", "Найз", "Nimesil", "nimesil", "Нимесил"]},
    {"canonical": "Tramadol", "openfda_term": "Tramadol",
     "category": "Pain/Fever",
     "variants": ["tramadol", "трамадол", "Ultram", "Tramal", "tramal"]},
    {"canonical": "Ketoprofen", "openfda_term": "Ketoprofen",
     "category": "Pain/Fever",
     "variants": ["ketoprofen", "кетопрофен", "Ketonal", "Fastum"]},

    # ─── STOMACH / GI ───────────────────────────────────────────
    {"canonical": "Omeprazole", "openfda_term": "Omeprazole",
     "category": "GI",
     "variants": ["omeprazole", "omeprazol", "омепразол", "օմեպրազոլ",
                  "Omez", "omez", "Омез", "Losec", "losec", "Лосек",
                  "Prilosec", "Ortanol"]},
    {"canonical": "Pantoprazole", "openfda_term": "Pantoprazole",
     "category": "GI",
     "variants": ["pantoprazole", "pantoprazol", "пантопразол",
                  "Controloc", "controloc", "Контролок", "Nolpaza"]},
    {"canonical": "Esomeprazole", "openfda_term": "Esomeprazole",
     "category": "GI",
     "variants": ["esomeprazole", "esomeprazol", "эзомепразол",
                  "Nexium", "nexium", "Нексиум"]},
    {"canonical": "Metoclopramide", "openfda_term": "Metoclopramide",
     "category": "GI",
     "variants": ["metoclopramide", "metoklopramid", "метоклопрамид",
                  "Cerucal", "cerucal", "Церукал", "Reglan"]},
    {"canonical": "Domperidone", "openfda_term": "Domperidone",
     "category": "GI",
     "variants": ["domperidone", "domperidon", "домперидон",
                  "Motilium", "motilium", "Мотилиум"]},
    {"canonical": "Simethicone", "openfda_term": "Simethicone",
     "category": "GI",
     "variants": ["simethicone", "simetikon", "симетикон",
                  "Espumisan", "espumisan", "Эспумизан"]},
    {"canonical": "Loperamide", "openfda_term": "Loperamide",
     "category": "GI",
     "variants": ["loperamide", "loperamid", "лоперамид",
                  "Imodium", "imodium", "Имодиум"]},
    {"canonical": "Bismuth subcitrate", "openfda_term": "Bismuth",
     "category": "GI",
     "variants": ["bismuth", "vismut", "висмут",
                  "De-Nol", "denol", "Де-Нол", "Novobismol"]},
    {"canonical": "Famotidine", "openfda_term": "Famotidine",
     "category": "GI",
     "variants": ["famotidine", "famotidin", "фамотидин",
                  "Kvamatel", "kvamatel", "Квамател", "Pepcid"]},
    {"canonical": "Activated Charcoal", "openfda_term": "Activated Charcoal",
     "category": "GI",
     "variants": ["activated charcoal", "aktivugol", "aktivirovannyy ugol",
                  "активированный уголь", "Карбоактив", "ակտիվ ածուխ"]},

    # ─── HEART / BLOOD PRESSURE ─────────────────────────────────
    {"canonical": "Amlodipine", "openfda_term": "Amlodipine",
     "category": "Cardiovascular",
     "variants": ["amlodipine", "amlodipin", "амлодипин", "ամլոդիպին",
                  "Norvasc", "norvasc", "Stamlo", "Tenox"]},
    {"canonical": "Lisinopril", "openfda_term": "Lisinopril",
     "category": "Cardiovascular",
     "variants": ["lisinopril", "лизиноприл", "լիզինոպրիլ",
                  "Prinivil", "Diroton", "diroton"]},
    {"canonical": "Enalapril", "openfda_term": "Enalapril",
     "category": "Cardiovascular",
     "variants": ["enalapril", "эналаприл", "Enap", "enap", "Энап",
                  "Renitec", "renitec"]},
    {"canonical": "Atorvastatin", "openfda_term": "Atorvastatin",
     "category": "Cardiovascular",
     "variants": ["atorvastatin", "аторвастатин", "ատորվաստատին",
                  "Lipitor", "lipitor", "Липитор", "Liprimar", "liprimar",
                  "Atoris", "atoris"]},
    {"canonical": "Metoprolol", "openfda_term": "Metoprolol",
     "category": "Cardiovascular",
     "variants": ["metoprolol", "метопролол",
                  "Egilok", "egilok", "Эгилок", "Betaloc", "Lopressor"]},
    {"canonical": "Bisoprolol", "openfda_term": "Bisoprolol",
     "category": "Cardiovascular",
     "variants": ["bisoprolol", "бисопролол",
                  "Concor", "concor", "Конкор", "Coronal"]},
    {"canonical": "Ramipril", "openfda_term": "Ramipril",
     "category": "Cardiovascular",
     "variants": ["ramipril", "рамиприл",
                  "Tritace", "tritace", "Тритаце", "Hartil"]},
    {"canonical": "Losartan", "openfda_term": "Losartan",
     "category": "Cardiovascular",
     "variants": ["losartan", "лозартан",
                  "Cozaar", "cozaar", "Козаар", "Lorista"]},
    {"canonical": "Valsartan", "openfda_term": "Valsartan",
     "category": "Cardiovascular",
     "variants": ["valsartan", "валсартан",
                  "Diovan", "diovan", "Диован", "Valsacor"]},
    {"canonical": "Carvedilol", "openfda_term": "Carvedilol",
     "category": "Cardiovascular",
     "variants": ["carvedilol", "карведилол",
                  "Coriol", "coriol", "Кориол", "Coreg", "Dilatrend"]},

    # ─── DIABETES ───────────────────────────────────────────────
    {"canonical": "Metformin", "openfda_term": "Metformin",
     "category": "Diabetes",
     "variants": ["metformin", "метформин", "մետֆորմին",
                  "Glucophage", "glucophage", "Глюкофаж", "Siofor"]},
    {"canonical": "Glibenclamide", "openfda_term": "Glyburide",
     "category": "Diabetes",
     "variants": ["glibenclamide", "glibenklamid", "глибенкламид",
                  "Maninil", "maninil", "Манинил", "glyburide"]},
    {"canonical": "Sitagliptin", "openfda_term": "Sitagliptin",
     "category": "Diabetes",
     "variants": ["sitagliptin", "ситаглиптин",
                  "Januvia", "januvia", "Янувия"]},
    {"canonical": "Insulin", "openfda_term": "Insulin",
     "category": "Diabetes",
     "variants": ["insulin", "инсулин", "ինսուլին",
                  "Humulin", "humulin", "NovoRapid", "Lantus", "Levemir"]},
    {"canonical": "Glimepiride", "openfda_term": "Glimepiride",
     "category": "Diabetes",
     "variants": ["glimepiride", "glimepirid", "глимепирид",
                  "Amaryl", "amaryl", "Амарил"]},

    # ─── RESPIRATORY / ALLERGY ──────────────────────────────────
    {"canonical": "Salbutamol", "openfda_term": "Albuterol",
     "category": "Respiratory",
     "variants": ["salbutamol", "сальбутамол",
                  "Ventolin", "ventolin", "Вентолин", "albuterol",
                  "Salbutamol Easyhaler"]},
    {"canonical": "Budesonide", "openfda_term": "Budesonide",
     "category": "Respiratory",
     "variants": ["budesonide", "budesonid", "будесонид",
                  "Pulmicort", "pulmicort", "Пульмикорт"]},
    {"canonical": "Montelukast", "openfda_term": "Montelukast",
     "category": "Respiratory",
     "variants": ["montelukast", "монтелукаст",
                  "Singulair", "singulair", "Сингуляр"]},
    {"canonical": "Bromhexine", "openfda_term": "Bromhexine",
     "category": "Respiratory",
     "variants": ["bromhexine", "bromgeksin", "бромгексин",
                  "Bisolvon", "bisolvon"]},
    {"canonical": "Ambroxol", "openfda_term": "Ambroxol",
     "category": "Respiratory",
     "variants": ["ambroxol", "амброксол",
                  "Lazolvan", "lazolvan", "Лазолван", "Ambrobene"]},
    {"canonical": "Acetylcysteine", "openfda_term": "Acetylcysteine",
     "category": "Respiratory",
     "variants": ["acetylcysteine", "atsetiltsistein", "ацетилцистеин",
                  "ACC", "АЦЦ", "Fluimucil", "Mucomyst"]},
    {"canonical": "Loratadine", "openfda_term": "Loratadine",
     "category": "Allergy",
     "variants": ["loratadine", "loratadin", "лоратадин",
                  "Claritin", "claritin", "Кларитин", "Loratin"]},
    {"canonical": "Cetirizine", "openfda_term": "Cetirizine",
     "category": "Allergy",
     "variants": ["cetirizine", "cetirizin", "цетиризин",
                  "Zyrtec", "zyrtec", "Зиртек", "Parlazin", "Letizen"]},

    # ─── MENTAL HEALTH ──────────────────────────────────────────
    {"canonical": "Fluoxetine", "openfda_term": "Fluoxetine",
     "category": "Mental Health",
     "variants": ["fluoxetine", "fluoksetin", "флуоксетин",
                  "Prozac", "prozac", "Прозак"]},
    {"canonical": "Sertraline", "openfda_term": "Sertraline",
     "category": "Mental Health",
     "variants": ["sertraline", "sertralin", "сертралин",
                  "Zoloft", "zoloft", "Золофт", "Asentra"]},
    {"canonical": "Diazepam", "openfda_term": "Diazepam",
     "category": "Mental Health",
     "variants": ["diazepam", "диазепам",
                  "Valium", "valium", "Валиум", "Relanium", "Реланиум",
                  "Seduxen"]},
    {"canonical": "Alprazolam", "openfda_term": "Alprazolam",
     "category": "Mental Health",
     "variants": ["alprazolam", "алпразолам",
                  "Xanax", "xanax", "Ксанакс"]},
    {"canonical": "Amitriptyline", "openfda_term": "Amitriptyline",
     "category": "Mental Health",
     "variants": ["amitriptyline", "amitriptilin", "амитриптилин",
                  "Saroten", "Elavil"]},
    {"canonical": "Haloperidol", "openfda_term": "Haloperidol",
     "category": "Mental Health",
     "variants": ["haloperidol", "галоперидол", "Haldol"]},

    # ─── THYROID / HORMONES ─────────────────────────────────────
    {"canonical": "Levothyroxine", "openfda_term": "Levothyroxine",
     "category": "Hormone",
     "variants": ["levothyroxine", "levotiroksin", "левотироксин",
                  "Eutirox", "eutirox", "Эутирокс",
                  "L-thyroxine", "L-тироксин", "Synthroid"]},
    {"canonical": "Prednisolone", "openfda_term": "Prednisolone",
     "category": "Hormone",
     "variants": ["prednisolone", "prednizolon", "преднизолон",
                  "պրեդնիզոլոն", "Medrol"]},
    {"canonical": "Dexamethasone", "openfda_term": "Dexamethasone",
     "category": "Hormone",
     "variants": ["dexamethasone", "deksametazon", "дексаметазон",
                  "Decadron"]},

    # ─── VITAMINS / SUPPLEMENTS ─────────────────────────────────
    {"canonical": "Vitamin D", "openfda_term": "Cholecalciferol",
     "category": "Vitamin",
     "variants": ["vitamin d", "vitamin d3", "витамин д", "витамин d",
                  "vit d", "Vigantol", "vigantol", "Вигантол",
                  "cholecalciferol", "Aquadetrim"]},
    {"canonical": "Vitamin C", "openfda_term": "Ascorbic Acid",
     "category": "Vitamin",
     "variants": ["vitamin c", "vit c", "витамин c", "витамин с",
                  "ascorbic acid", "askorbinka", "аскорбиновая кислота"]},
    {"canonical": "Magnesium", "openfda_term": "Magnesium",
     "category": "Vitamin",
     "variants": ["magnesium", "magnium", "магний",
                  "Magne B6", "magne b6", "Магне B6", "магне б6",
                  "Magnerot", "Magnefar"]},
    {"canonical": "Iron", "openfda_term": "Ferrous Sulfate",
     "category": "Vitamin",
     "variants": ["iron", "ferrum", "железо",
                  "Sorbifer", "sorbifer", "Сорбифер",
                  "Totema", "totema", "Тотема", "Ferretab", "Maltofer"]},
    {"canonical": "Folic acid", "openfda_term": "Folic Acid",
     "category": "Vitamin",
     "variants": ["folic acid", "folievaya kislota", "фолиевая кислота",
                  "folate", "folacin"]},
    {"canonical": "Calcium", "openfda_term": "Calcium Carbonate",
     "category": "Vitamin",
     "variants": ["calcium", "kalcij", "кальций",
                  "calcium d3", "Calcium D3 Nycomed",
                  "Кальций Д3 Никомед", "calcij d3 nikomed"]},

    # ─── SKIN / TOPICAL ─────────────────────────────────────────
    {"canonical": "Hydrocortisone", "openfda_term": "Hydrocortisone",
     "category": "Topical",
     "variants": ["hydrocortisone", "gidrokortizon", "гидрокортизон",
                  "Cortef", "Locoid"]},
    {"canonical": "Clotrimazole", "openfda_term": "Clotrimazole",
     "category": "Topical",
     "variants": ["clotrimazole", "klotrimazol", "клотримазол",
                  "Canesten", "canesten", "Канестен", "Lotrimin"]},
    {"canonical": "Acyclovir", "openfda_term": "Acyclovir",
     "category": "Antiviral",
     "variants": ["acyclovir", "atsiklovir", "ацикловир",
                  "Zovirax", "zovirax", "Зовиракс", "Herperax"]},
    {"canonical": "Fusidic Acid", "openfda_term": "Fusidic Acid",
     "category": "Topical",
     "variants": ["fusidic acid", "fuzidovaya kislota", "фусидовая кислота",
                  "Fucidin", "fucidin", "Фуцидин", "Fucibet"]},

    # ─── EYES / EARS ────────────────────────────────────────────
    {"canonical": "Tobramycin", "openfda_term": "Tobramycin",
     "category": "Eye/Ear",
     "variants": ["tobramycin", "tobramicin", "тобрамицин",
                  "Tobrex", "tobrex", "Тобрекс", "Tobradex"]},
]


def total_meds() -> int:
    return len(MEDICATION_CATALOG)


def total_variants() -> int:
    return sum(len(m["variants"]) for m in MEDICATION_CATALOG)
